#!/bin/bash
myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`;

flag=0

echo

function create_user() {
	useradd -M $uname
	echo "$uname:$pass" | chpasswd
	usermod -e $expdate $uname

	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
	myip2="s/xxxxxxxxx/$myip/g";	
	wget -qO /tmp/client.ovpn "https://raw.githubusercontent.com/elhad/cstup/master/1194-client.conf"
	sed -i 's/remote xxxxxxxxx 1194/remote xxxxxxxxx 443/g' /tmp/client.ovpn
	sed -i $myip2 /tmp/client.ovpn
	echo ""
	echo "========================="
	echo "Host IP : $myip"
	echo "Port    : 443/22/80"
	echo "Squid   : 8080/3128"
	echo "========================="
	echo "Script by Yujin Barboza , gunakan akun dengan bijak"
	echo "========================="
}

function renew_user() {
	echo "New expiration date for $uname: $expdate...";
	usermod -e $expdate $uname
}

function delete_user(){
	userdel $uname
}

function expired_users(){
	cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
	totalaccounts=`cat /tmp/expirelist.txt | wc -l`
	for((i=1; i<=$totalaccounts; i++ )); do
		tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
		username=`echo $tuserval | cut -f1 -d:`
		userexp=`echo $tuserval | cut -f2 -d:`
		userexpireinseconds=$(( $userexp * 86400 ))
		todaystime=`date +%s`
		if [ $userexpireinseconds -lt $todaystime ] ; then
			echo $username
		fi
	done
	rm /tmp/expirelist.txt
}

function not_expired_users(){
    cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
    totalaccounts=`cat /tmp/expirelist.txt | wc -l`
    for((i=1; i<=$totalaccounts; i++ )); do
        tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
        username=`echo $tuserval | cut -f1 -d:`
        userexp=`echo $tuserval | cut -f2 -d:`
        userexpireinseconds=$(( $userexp * 86400 ))
        todaystime=`date +%s`
        if [ $userexpireinseconds -gt $todaystime ] ; then
            echo $username
        fi
    done
	rm /tmp/expirelist.txt
}

function used_data(){
	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`
	myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`
	ifconfig $myint | grep "RX bytes" | sed -e 's/ *RX [a-z:0-9]*/Received: /g' | sed -e 's/TX [a-z:0-9]*/\nTransfered: /g'
}

	clear
	echo "--------------- Selamat datang di Server - IP: $myip ---------------"
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')

	echo -e "\e[032;1mCPU model:\e[0m $cname"
	echo -e "\e[032;1mNumber of cores:\e[0m $cores"
	echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
	echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
	echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
	echo -e "\e[032;1mSystem uptime:\e[0m $up"
	echo -e "\e[032;1mScript by:\e[0m Yujin Barboza | https://overses.net/"
	echo "------------------------------------------------------------------------------"
	echo "Seputar SSH & OpenVPN"
	echo -e "\e[38;5;198m[1]\e[38;5;82mBuat Akun SSH/OpenVPN"
	echo -e "\e[38;5;198m[2]\e[38;5;82mBuat Generate Akun SSH/OpenVPN"
	echo -e "\e[38;5;198m[3]\e[38;5;82mBuat Generate Akun Trial"
	echo -e "\e[38;5;198m[4]\e[38;5;82mBuat Ganti Password Akun SSH/VPN"
	echo -e "\e[38;5;198m[5]\e[38;5;82mBuat Tambah Masa Aktif Akun SSH/OpenVPN"
	echo -e "\e[38;5;198m[6]\e[38;5;82mBuat Hapus Akun SSH/OpenVPN"
	echo -e "\e[38;5;198m[7]\e[38;5;82mBuat Cek Login Dropbear & OpenSSH"
	echo -e "\e[38;5;198m[8]\e[38;5;82mBuat Auto Limit Multi Login"
	echo -e "\e[38;5;198m[9]\e[38;5;82mBuat Melihat detail user SSH & OpenVPN"
	echo -e "\e[38;5;198m[10]\e[38;5;82mDaftar Akun dan Expire Date"
	echo -e "\e[38;5;198m[12]\e[38;5;82mDelete Akun Expire"
	echo -e "\e[38;5;198m[12]\e[38;5;82mKill Multi Login"
	echo -e "\e[38;5;198m[13]\e[38;5;82mAuto Banned Akun"
	echo -e "\e[38;5;198m[14]\e[38;5;82mUnbanned Akun"
	echo -e "\e[38;5;198m[15]\e[38;5;82mMengunci Akun SSH & OpenVPN"
	echo -e "\e[38;5;198m[16]\e[38;5;82mMembuka user SSH & OpenVPN yang terkunci"
	echo -e "\e[38;5;198m[17]\e[38;5;82mMelihat daftar user yang terkick oleh perintah user-limit"
	echo -e "\e[38;5;198m[18]\e[38;5;82mMelihat daftar user yang terbanned oleh perintah user-ban"
	echo -e "\e[38;5;198m[19]\e[38;5;82mBuat Akun PPTP VPN"
	echo -e "\e[38;5;198m[20]\e[38;5;82mHapus Akun PPTP VPN"
	echo -e "\e[38;5;198m[21]\e[38;5;82mLihat Detail Akun PPTP VPN "
	echo -e "\e[38;5;198m[22]\e[38;5;82m Cek login PPTP VPN "
	echo -e "\e[38;5;198m[23]\e[38;5;82m Lihat Daftar User PPTP VPN"
	echo -e "\e[38;5;198m[24]\e[38;5;82mCek Lokasi User "
	echo -e "\e[38;5;198m[25]\e[38;5;82mSet Auto Reboot"
	echo -e "\e[38;5;198m[26]\e[38;5;82m Speedtest"
	echo -e "\e[38;5;198m[27]\e[38;5;82mCek Ram "
	echo -e "\e[38;5;198m[28]\e[38;5;82m Edit Banner"
	echo -e "\e[38;5;198m[29]\e[38;5;82m Edit Port"
	echo -e "\e[38;5;198m[30]\e[38;5;82mRestart"
	echo -e "\e[38;5;198m[31]\e[38;5;82m Benchmark"
	echo -e "\e[38;5;198m[32]\e[38;5;82mUbah Pasword"
	echo -e "\e[38;5;198m[33]\e[38;5;82mUbah Hostname "
	echo -e "\e[38;5;198m[34]\e[38;5;82mReboot Server "
	echo -e "\e[38;5;198m[35]\e[38;5;82mLog Install"
	echo -e "\e[38;5;198m[36]\e[38;5;82miagnosa"
	echo ""
	echo -e "\e[38;5;198m[37] \e[38;5;82m x\e[0m0 Exit"
	read -p "Masukkan pilihan anda, kemudian tekan tombol ENTER: " option1
	case $option1 in
        1)  
          clear
          buatakun.sh
          ;;
        2)  
          clear
          generate.sh
          ;;
        3)	
          clear
          trial.sh
	  ;;	
        4)
          clear
          userpass.sh
          ;;
        5)
          clear
          userrenew.sh
			;;
         6)
           clear
           userdelete.sh
           ;;		
	 7)
	   clear
	   userlogin.sh
	   ;;
	 8)
           clear
	   autolimit.sh
	   ;;	
	 9)
	   clear
           userdetail.sh
           ;;
        10)
           clear
           user-list.sh
           ;;
        11)
           clear
           deleteuserexpire.sh
	   ;;
	12)
	   clear
	   #!/bin/bash
           # Created by https://www.overses.net
           # Dilarang Keras Mengambil/mencuplik/mengcopy sebagian atau seluruh script ini.
           # Hak Cipta overses.net (Dilindungi Undang-Undang nomor 19 Tahun 2002)
           red='\e[1;31m'
           green='\e[0;32m'
           NC='\e[0m'
           echo "Connecting to overses.net..."
           sleep 0.2
           echo "Checking Permision..."
           sleep 0.3
           echo -e "${green}Permission Accepted...${NC}"
           sleep 1
           echo""
	   read -p "Isikan Maximal User Login (1-2): " MULTILOGIN
	   echo "    AUTO KILL MULTI LOGIN    "    
	   echo "-----------------------------"
           autokilluser.sh  $MULTILOGIN
	   autokill.sh  $MULTILOGIN
           echo "-----------------------------"
           echo "AUTO KILL MULTI LOGIN SELESAI"
           ;;
        13)
           clear
           userban.sh
	   ;;
	14)
           clear
           userunban.sh
	   ;;
        15)
	   clear
           userlock.sh
	   ;;
        16)
           clear
           userunlock.sh
	   ;;
	17)
	   clear
	   loglimit.sh
	   ;;
	18)
           clear
           logban.sh
	   ;;
        19)
	   clear
           useraddpptp.sh
	   ;;
        20)
	   clear
           userdeletepptp.sh
           ;;
	21)
	   clear
           detailpptp.sh
           ;;
        22)
           clear
           userloginpptp.sh
	   ;;
        23)
           clear
           alluserpptp.sh
	   ;;
        24)
	   clear
	   userlogin.sh
           echo "Contoh: 49.0.35.16 lalu Enter"
           read -p "Ketik Salah Satu Alamat IP User: " userip
           curl ipinfo.io/$userip
           ;;
	25)
	   clear
           autoreboot.sh
           ;;
	26)
	   clear
           #!/bin/bash
           red='\e[1;31m'
           green='\e[0;32m'
           blue='\e[1;34m'
           NC='\e[0m'
           echo "Connecting to overses.net..."
           sleep 0.2
           echo "Checking Permision..."
           sleep 0.3
           echo -e "${green}Permission Accepted...${NC}"
           sleep 1
           echo""
           echo "Speed Tes Server"
           speedtest.py.sh
           echo ""
	   echo "Script Created by https://www.overses.net"
           echo "Terimakasih sudah berlangganan di overses.net"
           ;;
        27)
           clear
           ram.sh
           ;;
        28)
	  clear
	  echo -e "1.) Simpan text (CTRL + X, lalu ketik Y dan tekan Enter) "  | tee -a log-install.txt
          echo -e "2.) Membatalkan edit text (CTRL + X, lalu ketik N dan tekan Enter)"  | tee -a log-install.txt
          echo "-----------------------------------------------------------"  | tee -a log-install.txt
          read -p "Tekan ENTER untuk melanjutkan........................ "
          nano /bannerssh
          /etc/init.d/dropbear restart
	  ;;
       29)
          clear
          ubahport.sh
	  ;;
       30)	
          clear
          restart.sh
	  ;;	
       31)
	  clear
          wget freevps.us/downloads/bench.sh -O - -o /dev/null|bash
          ;;
       32)
          clear
	  echo "Masukan Password VPS, yang mau diganti :"
	  passwd
	  ;;	
       33)
	  clear
	  echo "Masukan HOSTNAME VPS, yang mau diganti :"
          echo "contoh : " hostname ibnu 
          ;;
       34)
	  clear
	  reboot
          ;;
       35)
	  clear
	  log-install.sh
          ;;
       36)
          clear
          diagnosa.sh
	  ;;
       37)
          wget -O update.sh https://raw.githubusercontent.com/ehomecore91/setup-code/master/update.sh && chmod +x update.sh && ./update.sh
          ;;
        x)
          ;;
        *) menu;;
        esac
